language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by defaul, so we need to install it ourselves
      - libgconf-2-4
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - .cache
    - node_modules
# env:
#   - DOMAIN=localhost
#   - DOMAIN_FULL=http://localhost
#   - CLIENT_PORT=3000
#   - SOCKET_PORT=4000
#   - GQL_PORT=4000
install:
  - npm run heroku-postbuild
  - npm ci
before_script:
  - npm start &
script:
  - npm i
  - npm run test --record